const mongoose=require('mongoose')

const userSchema=mongoose.Schema({
      firstName:{
        type:String,
        required:true
      },
      lastName:{
        type:String,
        required:true
      },
      gender:{
        type:String,
      },
      email:{
        type:String,
        required:true
      },
      password:
      {
         type:String,
         required:true
      },
      aboutyou:
      {
         type:String,
      },
      projects:[
          {
             title:
             {
                 type:String,
                 required:true
             },
             description:
             {
                  type:String,
                  required:true
             },
             link:
             {
                 type:String,
                 required:true
             }
          }
      ],
      showedIntrestIn:[
          {
             postId:{
                type:String,
                required:true
             }
          }
      ],  
})

module.exports=mongoose.model('user',userSchema)